---

- hosts: all
  gather_facts: false
  remote_user: root
  roles:
  #- ssh-copy-id
  - common

#- hosts: controller
#  gather_facts: true
#  remote_user: root
#  roles:
#  - ssh-copy-id
  #- haproxy
  # - rabbitmq
  # - mariadb
  # - keystone
  # - glance
  # - nova
  # - neutron
  # - cinder

# - hosts: compute
#   gather_facts: true
#   remote_user: root
#   roles:
#   - nova-compute
#   - neutron-compute

# - hosts: cinder-volume
#   gather_facts: true
#   remote_user: root
#   roles:
#   - cinder-volume
