---


- name: start service
  service: name={{ item }} state=started enabled=yes
  with_items:
  - memcached
  - httpd
  tags: keystone-run

- name: register service endpoint
  template: src=create.sh.j2 dest=/tmp/create.sh owner=root group=root mode=0755
  when: hostname == "con-itools-node-01"
  tags: keystone-register

- name: register service endpoint
  shell: /bin/sh /tmp/create.sh
  register: create_sh
  when: hostname == "con-itools-node-01"
  tags: keystone-register

- name: create admin-openrc.sh
  template: src=admin-openrc.sh.j2 dest=/root/admin-openrc.sh force=yes
  when: hostname == "con-itools-node-01"
  tags: keystone-sh

- name: create demo-openrc.sh
  template: src=demo-openrc.sh.j2 dest=/root/demo-openrc.sh force=yes
  when: hostname == "con-itools-node-01"
  tags: keystone-sh

- debug: msg={{ create_sh }}
